services:

  flask:
    build:
      context: ./flask_app
      dockerfile: Dockerfile
    container_name: flask
    volumes:
      - ./flask_app:/app
    restart: unless-stopped
    networks:
      - red

  apache:
    build:
      context: ./apache
      dockerfile: Dockerfile
    container_name: apache
    ports:
      - "80:80"
    depends_on:
      - flask
    restart: unless-stopped
    networks:
      - red

networks:
  red:
    driver: bridge